package ai.cheatcoders.analytic.controller;

import ai.cheatcoders.analytic.service.OrchestratorService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/api/v1/orchestrator")
public class OrchestratorController {

    private final OrchestratorService orchestrator;

    public OrchestratorController(OrchestratorService orchestrator) {
        this.orchestrator = orchestrator;
    }

    @PostMapping("/nl-query")
    public ResponseEntity<?> nlQuery(@RequestBody Map<String, Object> body) {
        String table = (String) body.get("table");
        String question = (String) body.get("question");
        boolean explain = Boolean.parseBoolean(String.valueOf(body.getOrDefault("explain", "false")));
        if (table == null || question == null) return ResponseEntity.badRequest().body(Map.of("error", "table and question required"));

    try {
        OrchestratorService.NLResult res = orchestrator.handleNaturalLanguageQuery(table, question, explain);
        return ResponseEntity.ok(Map.of(
            "sql", res.sql,
            "rows", res.rows,
            "explanation", res.explanation
        ));
    } catch (IllegalArgumentException iae) {
        return ResponseEntity.badRequest().body(Map.of("error", "Unsafe or invalid SQL generated by LLM"));
    }
    }
}
