spring.datasource.url=jdbc:postgresql://localhost:5432/pivot_analytics?useUnicode=true&characterEncoding=UTF-8&stringtype=unspecified
spring.datasource.username=skyperfect
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
ai.service.url=http://localhost:8082